### ISSUE TITLE
Unexpected token ( 

### ISSUE THREAD

**Issue by arushijain45** [estrada9166/server-authentication-next.js#2]
While running this code without performing any changes, I am getting following error:

> const isLoggedIn = async (req, res, next) => {
>                            ^
> SyntaxError: Unexpected token (
>     at createScript (vm.js:56:10)
>     at Object.runInThisContext (vm.js:97:10)
>     at Module._compile (module.js:542:28)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:383:7)
>     at startup (bootstrap_node.js:149:9)

Can you please tell me why is this so?

**Comment by arushijain45** [comment]
Oh My Bad! I was using `v6.12.0` On updating the node version it works. Thank you for your feedback.
