### ISSUE TITLE
Syntax error at the isLoggedIn function on npm run dev

### ISSUE THREAD

**Issue by philmetzger** [estrada9166/server-authentication-next.js#3]
```
Phil@Phil-PC MINGW64 /c/projects/server-authentication-next.js (master)
$ npm run dev

> authentication.jwt@1.0.0 dev C:\projects\server-authentication-next.js
> node server.js

C:\projects\server-authentication-next.js\server.js:16
const isLoggedIn = async (req, res, next) => {
                         ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! authentication.jwt@1.0.0 dev: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the authentication.jwt@1.0.0 dev script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the authentication.jwt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs authentication.jwt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls authentication.jwt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\server-authentication-next.js\npm-debug.log

```

When I try start the server, i get the above message. any idea why? npm install did run through successfully from what I can tell too.

**Comment by estrada9166** [comment]
Which version of node are you using? it works for me with v7.8.0 🙂.... You can use nvm[https://github.com/creationix/nvm] to set it...

**Comment by philmetzger** [comment]
ah yes that fixes it. Upgraded to v8.9.1 even :)

Great job btw, was looking for a concept how authentication could be best done well and this example is just that!
